# Generated by Django 5.0.6 on 2024-05-21 06:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="vendor_code",
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
