# Generated by Django 5.0.6 on 2024-05-21 06:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_vendor_vendor_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="po_number",
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
